todo/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from todo.extensions import db
from sqlalchemy.orm import validates


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)
    todos = db.relationship("Todo")

    @validates("email")
    def validate_email(self, key, email):
        if len(email.strip()) <= 3:
            raise ValueError("needs to have an email")
        return email

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password, method="sha256")

    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

    def __repr__(self):
        return (
            f"<(User(id={self.id}, email={repr(self.email)}, todos={repr(self.todos)})>"
        )


class Todo(db.Model):

    __tablename__ = "todos"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    completed = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"<(Todo(id={self.id}, name={repr(self.name)}, user_id={self.user_id})>"

    @validates("name")
    def validate_name(self, key, name):
        if len(name.strip()) <= 3:
            raise ValueError("needs to have a name")
        return name

todo/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField
from wtforms.validators import Length, required, EqualTo, email
from werkzeug.security import check_password_hash
from todo.models import User

# look at user validation, how it was done in my other todo app vs yumroad vs miguel
class LoginForm(FlaskForm):
    email = StringField("Email", validators=[required()])
    password = PasswordField("Password", validators=[required()])

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if not user or not check_password_hash(user.password, self.password.data):
            self.email.errors.append("Invalid email or password.")


class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[email(), required(), Length(min=4)])
    password = PasswordField(
        "Password",
        validators=[
            required(),
            Length(min=4),
            EqualTo("confirm", message="Passwords must match"),
        ],
    )
    confirm = PasswordField("Confirm Password")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            self.email.errors.append("That email already has an account.")


class ToDoForm(FlaskForm):
    todo = StringField("New to do:", validators=[required(), Length(min=4, max=60)])

todo/__init__.py
from flask import Flask
from todo.config import configurations
from todo.blueprints.landing import landing_bp
from todo.blueprints.users import user_bp
from todo.extensions import db, login_manager, csrf, migrate


def create_app(environment_name="dev"):
    app = Flask(__name__)
    app.config.from_object(configurations[environment_name])

    db.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)

    app.register_blueprint(landing_bp)
    app.register_blueprint(user_bp)

    return app

todo/blueprints/landing.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from todo.forms import ToDoForm
from todo.models import User, Todo
from todo.extensions import db

landing_bp = Blueprint("landing", __name__)


@landing_bp.route("/", methods=["GET", "POST"])
def index():

    form = ToDoForm()

    if form.validate_on_submit():
        current_user.todos.append(Todo(name=form.todo.data))
        db.session.commit()
        return redirect(url_for("landing.index"))

    return render_template("landing/index.html", form=form)

todo/blueprints/users.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import (
    logout_user,
    login_user,
    login_required,
    current_user,
)
from todo.models import User, Todo
from todo.forms import RegisterForm, LoginForm
from todo.extensions import db, login_manager, csrf

user_bp = Blueprint("user", __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@login_manager.unauthorized_handler
def unauthorized():
    # store the url they were trying to visit in the session
    session["after_login"] = request.url
    flash("You need to login", "warning")
    return redirect(url_for("user.login"))


@user_bp.route("/register", methods=["GET", "POST"])
def register():

    if current_user.is_authenticated:
        flash("You are already logged in", "warning")
        return redirect(url_for("landing.index"))

    form = RegisterForm()
    if form.validate_on_submit():

        user = User(email=form.email.data)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()
        login_user(user)

        flash("Registered successfully", "success")

        return redirect(url_for("landing.index"))

    return render_template("users/register.html", form=form)


@user_bp.route("/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        flash("You are already logged in", "warning")
        return redirect(url_for("landing.index"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        login_user(user)
        return redirect(session.get("after_login") or url_for("landing.index"))

    return render_template("users/login.html", form=form)


@user_bp.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("landing.index"))


# TODO: move these


@user_bp.route("/delete", methods=["POST"])
@login_required
@csrf.exempt
def delete():

    # checks to see if the todo matches the user that's in the session
    todo = Todo.query.filter_by(
        user_id=current_user.id, id=request.form["delete"]
    ).first()

    if todo:
        db.session.delete(todo)
        db.session.commit()

    return redirect(url_for("landing.index"))


@user_bp.route("/toggle", methods=["POST"])
@login_required
@csrf.exempt
def toggle():

    # checks to see if the todo matches the user that's in the session
    todo = Todo.query.filter_by(
        user_id=current_user.id, id=request.form["toggle"]
    ).first()

    if todo:
        todo.completed = not todo.completed
        db.session.commit()

    return redirect(url_for("landing.index"))

todo/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    <label for="{{ field.name }}"> {{ field.label }} </label>
    {% if field.description %}
    <small classname="text-muted" for="{{ field.name }}">({{ field.description }})</small>
    {% endif %}
    {{ field(class_=' '.join(['form-control', 'is-invalid' if field.errors else '']), **kwargs)|safe }}
    <ul class="invalid-feedback errors">
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
</div>
{% endmacro %}

todo/templates/_macros.html
{% macro render_flashes() %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="container mt-4">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        </button>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endmacro %}

todo/templates/base_layout.html
{% from "_macros.html" import render_flashes %}

<html>

<head>
    <title>{% block title %}{% endblock %} | To do</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="csrf-token" content="{{  csrf_token() }}">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('landing.index') }}">ToDoSimple</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#">
                    {{ current_user.email }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.logout') }}">
                    Log out
                </a>
            </li>
            {% else %}
            <li class=" nav-item">
                <a class="nav-link" href="{{ url_for('user.login') }}">
                    Log In
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>

        </div>
    </nav>

    <!-- <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
        <nav class="my-2 my-md-0 mr-md-3">

        </nav>
        <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div> -->

    <!-- <nav class="navbar navbar-light bg-light justify-content-between navbar-toggleable-sm">
        <a href="{{ url_for('landing.index') }}" class="navbar-brand" id="logo">TodoSimple</a>
        <div class="navbar-item">
            {% if current_user.is_authenticated %}
            <a class="ml-3 navbar-link"> {{ current_user.username }}</a>
            <a class="nav-link" href="{{ url_for('user.logout') }}">Log out</a>
            {% else %}
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
            <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
            {% endif %}
        </div>
    </nav> -->
    {{ render_flashes() }}
    <div class="container mt-3 text-center">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>

</html>

todo/templates/landing/index.html
{% extends 'base_layout.html' %}
{% from "_formhelpers.html" import render_field %}


{% block content %}

{% if current_user.is_authenticated %}

<p> Welcome, {{ current_user.email }}</p>
<br>

<h4>To do list</h4>
<hr width="50%">

<ul style="list-style: none;">
    {% for todo in current_user.todos %}
    <li>
        {% if todo.completed %}
        <strike>
            {% endif %}

            {{ todo.name }}

            {% if todo.completed %}
        </strike>
        {% endif %}
        <form method="post" action="/toggle">
            <input type="hidden" name="toggle" value="{{ todo.id }}">
            <button type="submit" class="btn btn-info btn-sm"> Toggle </button>
        </form>
        <form method="post" action="/delete">
            <input type="hidden" name="delete" value="{{ todo.id }}">
            <button type="submit" class="btn btn-outline-info btn-sm">Delete</button>
        </form>

    </li>

    {% endfor %}
</ul>

<hr width="50%">

<form method="POST">
    {{ form.csrf_token }}

    {{ render_field(form.todo) }}
    <button type="submit" class="btn btn-outline-dark btn-block">Submit</button>
</form>

{% else %}
Hello, You've just stumbled upon the best to do app ever! <br>
Please register or log in to start tracking your to-dos.
{% endif %}
{% endblock %}

todo/templates/users/login.html
{% extends 'base_layout.html' %}
{% from "_formhelpers.html" import render_field %}

{% block title %} Login {% endblock %}

{% block content %}

<form class="form-signin w-25" method="POST">

    {{ form.csrf_token }}


    {{ render_field(form.email) }}
    {{ render_field(form.password) }}

    <button id="signin" class="btn btn-info btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2021</p>
</form>

{% endblock %}

todo/templates/users/register.html
{% extends 'base_layout.html' %}

{% from "_formhelpers.html" import render_field %}

{% block title %} Register {% endblock %}

{% block content %}
<form class="form-signin w-25" method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ render_field(form.confirm) }}

    <button type="submit" class="btn btn-info btn-block"> Sign up </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2021</p>

</form>
{% endblock %}